<?php

class DepartmentsTableSeeder extends Seeder
{

	public function run()
	{
		// Uncomment the below to wipe the table clean before populating
		// DB::table('courses')->truncate();

		$departments = array(
			['id'   	      => 1,
			'faculty_id'      => 1,
			'name'        	  => 'Western Languages',
			'created_at'  	  => date('Y-m-d H:i:s'),
			'updated_at'  	  => date('Y-m-d H:i:s')],
			['id'   	      => 2,
			'faculty_id'      => 1,
			'name'        	  => 'Western Languages (Chinese Language)',
			'created_at'  	  => date('Y-m-d H:i:s'),
			'updated_at'  	  => date('Y-m-d H:i:s')],
			['id'   	      => 3,
			'faculty_id'      => 1,
			'name'        	  => 'Eastern Languages (The Russian Language and Literature)',
			'created_at'  	  => date('Y-m-d H:i:s'),
			'updated_at'  	  => date('Y-m-d H:i:s')],
			['id'   	      => 4,
			'faculty_id'      => 1,
			'name'        	  => 'Educational Science',
			'created_at'  	  => date('Y-m-d H:i:s'),
			'updated_at'  	  => date('Y-m-d H:i:s')],
			['id'   	      => 5,
			'faculty_id'      => 1,
			'name'        	  => 'Philosophy',
			'created_at'  	  => date('Y-m-d H:i:s'),
			'updated_at'  	  => date('Y-m-d H:i:s')],
			['id'   	      => 6,
			'faculty_id'      => 1,
			'name'        	  => 'Sociology',
			'created_at'  	  => date('Y-m-d H:i:s'),
			'updated_at'  	  => date('Y-m-d H:i:s')],
			['id'   	      => 7,
			'faculty_id'      => 1,
			'name'        	  => 'History',
			'created_at'  	  => date('Y-m-d H:i:s'),
			'updated_at'  	  => date('Y-m-d H:i:s')],
			['id'   	      => 8,
			'faculty_id'      => 1,
			'name'        	  => 'Turkology',
			'created_at'  	  => date('Y-m-d H:i:s'),
			'updated_at'  	  => date('Y-m-d H:i:s')],
			['id'   	      => 9,
			'faculty_id'      => 1,
			'name'        	  => 'Translations',
			'created_at'  	  => date('Y-m-d H:i:s'),
			'updated_at'  	  => date('Y-m-d H:i:s')],
			['id'   	      => 10,
			'faculty_id'      => 2,
			'name'        	  => 'Mathematics',
			'created_at'  	  => date('Y-m-d H:i:s'),
			'updated_at'  	  => date('Y-m-d H:i:s')],
			['id'   	      => 11,
			'faculty_id'      => 2,
			'name'        	  => 'Applied Mathematics and Informatics',
			'created_at'  	  => date('Y-m-d H:i:s'),
			'updated_at'  	  => date('Y-m-d H:i:s')],
			['id'   	      => 12,
			'faculty_id'      => 2,
			'name'        	  => 'Biology',
			'created_at'  	  => date('Y-m-d H:i:s'),
			'updated_at'  	  => date('Y-m-d H:i:s')],
			['id'   	      => 13,
			'faculty_id'      => 3,
			'name'        	  => 'Painting',
			'created_at'  	  => date('Y-m-d H:i:s'),
			'updated_at'  	  => date('Y-m-d H:i:s')],
			['id'   	      => 14,
			'faculty_id'      => 3,
			'name'        	  => 'Graphics',
			'created_at'  	  => date('Y-m-d H:i:s'),
			'updated_at'  	  => date('Y-m-d H:i:s')],
			['id'   	      => 15,
			'faculty_id'      => 4,
			'name'        	  => 'Economy',
			'created_at'  	  => date('Y-m-d H:i:s'),
			'updated_at'  	  => date('Y-m-d H:i:s')],
			['id'   	      => 16,
			'faculty_id'      => 4,
			'name'        	  => 'Management',
			'created_at'  	  => date('Y-m-d H:i:s'),
			'updated_at'  	  => date('Y-m-d H:i:s')],
			['id'   	      => 17,
			'faculty_id'      => 4,
			'name'        	  => 'Finance',
			'created_at'  	  => date('Y-m-d H:i:s'),
			'updated_at'  	  => date('Y-m-d H:i:s')],
			['id'   	      => 18,
			'faculty_id'      => 4,
			'name'        	  => 'International Relations',
			'created_at'  	  => date('Y-m-d H:i:s'),
			'updated_at'  	  => date('Y-m-d H:i:s')],
			['id'   	      => 19,
			'faculty_id'      => 4,
			'name'        	  => 'Finance and Banking',
			'created_at'  	  => date('Y-m-d H:i:s'),
			'updated_at'  	  => date('Y-m-d H:i:s')],
			['id'   	      => 20,
			'faculty_id'      => 5,
			'name'        	  => 'Journalism',
			'created_at'  	  => date('Y-m-d H:i:s'),
			'updated_at'  	  => date('Y-m-d H:i:s')],
			['id'   	      => 21,
			'faculty_id'      => 5,
			'name'        	  => 'Public Relations and Advertising',
			'created_at'  	  => date('Y-m-d H:i:s'),
			'updated_at'  	  => date('Y-m-d H:i:s')],
			['id'   	      => 22,
			'faculty_id'      => 5,
			'name'        	  => 'Radio, TV and Cinema',
			'created_at'  	  => date('Y-m-d H:i:s'),
			'updated_at'  	  => date('Y-m-d H:i:s')],
			['id'   	      => 23,
			'faculty_id'      => 6,
			'name'        	  => 'Chemical Engineering',
			'created_at'  	  => date('Y-m-d H:i:s'),
			'updated_at'  	  => date('Y-m-d H:i:s')],
			['id'   	      => 24,
			'faculty_id'      => 6,
			'name'        	  => 'Computer Engineering',
			'created_at'  	  => date('Y-m-d H:i:s'),
			'updated_at'  	  => date('Y-m-d H:i:s')],
			['id'   	      => 25,
			'faculty_id'      => 6,
			'name'        	  => 'Ecological Engineering',
			'created_at'  	  => date('Y-m-d H:i:s'),
			'updated_at'  	  => date('Y-m-d H:i:s')],
			['id'   	      => 26,
			'faculty_id'      => 6,
			'name'        	  => 'Food Engineering',
			'created_at'  	  => date('Y-m-d H:i:s'),
			'updated_at'  	  => date('Y-m-d H:i:s')],
		);

		// Uncomment the below to run the seeder
		DB::table('departments')->insert($departments);
	}

}